### ISSUE TITLE
dcli throws exception when releasing.

### ISSUE THREAD

**Issue by bsutton** [onepub-dev/pubspec_manager#1]
When releasing dcli.
Unhandled exception:
Error: The passed version is invalid: Could not parse version "'>=3.0.0 <4.0.0'". Unknown text at "'>=3.0.0 <4.0.0'".
#0      VersionAttached.version= (package:pubspec_manager/src/version_attached.dart:64:7)
#1      EnvironmentAttached.sdk= (package:pubspec_manager/src/environment_attached.dart:82:10)

**Comment by bsutton** [comment]
resolved.
